In [80]:
import pandas as pd
import numpy as np 
df = pd.read_excel("excel/연세대학교 신촌캠퍼스 22년 1학기 강의목록.xlsx")
df = df.rename(
        columns={
            '계획서계획서':'계획서', 
            '학년학년':'학년', 
            '학정번호학정번호':'강의고유번호', 
            '교과목명교과목명':'강의명', 
            '담당교수담당교수':'교수명', 
            '학점학점':'학점', 
            '종별종별':'이수구분', 
            '강의평강의평':'강의평', 
            '담은 인원담은 인원':'정원', 
            '유의사항유의사항':'특이사항'
        }
    )

def lectureNumber(df):
    df['강의고유번호'] = df['강의고유번호'].str.split('-').str.get(0)     # '-' 기준으로 나누고 첫번째만 추출
    return df
df=lectureNumber(df)
df

,계획서,학년,이수구분,강의고유번호,학점,강의명,교수명,강의시간강의시간,강의실강의실,강의평,정원,특이사항
0,조회,0,공기,YCA1003,0.0,채플(3),"이대성,정종훈,정미현",NaN,NaN,NaN,5.0,"100%온라인:동영상콘텐츠강의, 온라인강좌, P/NP평가 과목"
1,조회,0/1,공기/CC,YCA1003,0.0,채플(3),"이대성,정종훈,정미현",NaN,NaN,NaN,5.0,"100%온라인:동영상콘텐츠강의, 온라인강좌, UIC, 영어채플, P/NP평가 과목"
2,조회,0/9,공기/학기,YCA1011,0.0,예배채플(1),"정종훈,이대성,정미현",수10,루101,NaN,1.0,"대면강의, 기독교인의 신앙 성숙을 위한 예배 채플(연세수요저녁예배의 정규 채플화),..."
3,조회,2,전필,HIS2002,0.0,문화유적답사(1),하일식,화10,실시간온라인,NaN,25.0,"블랜딩:대면-비대면(실시간온라인), [답사] 2020학년 이전 입학자(~20학번) ..."
4,조회,0,CC/공기,YCA1001,0.0,채플(1),곽호철,NaN,NaN,NaN,38.0,P/NP평가 과목
...,...,...,...,...,...,...,...,...,...,...,...,...
3501,조회,0,학선,KLI1002,6.0,INTENSIVE KOREAN LANGUAGE (LEVEL 2),곽지영,"월8,9,수8,9,금8,9",실시간온라인,NaN,0.0,"100%온라인:실시간온라인강의, 절대평가"
3502,조회,0,학선,KLI1003,6.0,INTENSIVE KOREAN LANGUAGE (LEVEL 3),곽지영,"월8,9,수8,9,금8,9",실시간온라인,NaN,0.0,"100%온라인:실시간온라인강의, 절대평가"
3503,조회,0,학선,KLI1004,6.0,INTENSIVE KOREAN LANGUAGE (LEVEL 4),곽지영,"월8,9,수8,9,금8,9",실시간온라인,NaN,0.0,"100%온라인:실시간온라인강의, 절대평가"
3504,조회,0,학선,KLI1005,6.0,INTENSIVE KOREAN LANGUAGE (LEVEL 5),곽지영,"월8,9,수8,9,금8,9",실시간온라인,NaN,1.0,"100%온라인:실시간온라인강의, 절대평가"
3505,조회,0,학선,KLI1006,6.0,INTENSIVE KOREAN LANGUAGE (LEVEL 6),곽지영,"월8,9,수8,9,금8,9",실시간온라인,NaN,0.0,"100%온라인:실시간온라인강의, 절대평가"

In [85]:
import pandas as pd
import numpy as np 
df = pd.read_excel("excel/연세대학교 신촌캠퍼스 22년 1학기 강의목록.xlsx")
df = df.rename(
        columns={
            '계획서계획서':'계획서', 
            '학년학년':'학년', 
            '학정번호학정번호':'강의고유번호', 
            '교과목명교과목명':'강의명', 
            '담당교수담당교수':'교수명', 
            '학점학점':'학점', 
            '종별종별':'이수구분', 
            '강의평강의평':'강의평', 
            '담은 인원담은 인원':'정원', 
            '유의사항유의사항':'특이사항'
        }
    )
#df.assign(df=df['교수명'].str.split(",")).explode('교수명')
#def professorName(df):
#    df['교수명']=df['교수명'].str.split(',').explode('교수명')
#    return df
#df=professorName(df)
#df

,계획서,학년,이수구분,강의고유번호,학점,강의명,교수명,강의시간강의시간,강의실강의실,강의평,정원,특이사항
0,조회,0,공기,YCA1003-01-00,0.0,채플(3),이대성,NaN,NaN,NaN,5.0,"100%온라인:동영상콘텐츠강의, 온라인강좌, P/NP평가 과목"
1,조회,0/1,공기/CC,YCA1003-02-00,0.0,채플(3),정종훈,NaN,NaN,NaN,5.0,"100%온라인:동영상콘텐츠강의, 온라인강좌, UIC, 영어채플, P/NP평가 과목"
2,조회,0/9,공기/학기,YCA1011-01-00,0.0,예배채플(1),정미현,수10,루101,NaN,1.0,"대면강의, 기독교인의 신앙 성숙을 위한 예배 채플(연세수요저녁예배의 정규 채플화),..."
3,조회,2,전필,HIS2002-01-00,0.0,문화유적답사(1),이대성,화10,실시간온라인,NaN,25.0,"블랜딩:대면-비대면(실시간온라인), [답사] 2020학년 이전 입학자(~20학번) ..."
4,조회,0,CC/공기,YCA1001-01-00,0.0,채플(1),정종훈,NaN,NaN,NaN,38.0,P/NP평가 과목
...,...,...,...,...,...,...,...,...,...,...,...,...
3501,조회,0,학선,KLI1002-01-00,6.0,INTENSIVE KOREAN LANGUAGE (LEVEL 2),이호규,"월8,9,수8,9,금8,9",실시간온라인,NaN,0.0,"100%온라인:실시간온라인강의, 절대평가"
3502,조회,0,학선,KLI1003-01-00,6.0,INTENSIVE KOREAN LANGUAGE (LEVEL 3),이호규,"월8,9,수8,9,금8,9",실시간온라인,NaN,0.0,"100%온라인:실시간온라인강의, 절대평가"
3503,조회,0,학선,KLI1004-01-00,6.0,INTENSIVE KOREAN LANGUAGE (LEVEL 4),이호규,"월8,9,수8,9,금8,9",실시간온라인,NaN,0.0,"100%온라인:실시간온라인강의, 절대평가"
3504,조회,0,학선,KLI1005-01-00,6.0,INTENSIVE KOREAN LANGUAGE (LEVEL 5),이호규,"월8,9,수8,9,금8,9",실시간온라인,NaN,1.0,"100%온라인:실시간온라인강의, 절대평가"
3505,조회,0,학선,KLI1006-01-00,6.0,INTENSIVE KOREAN LANGUAGE (LEVEL 6),이명숙,"월8,9,수8,9,금8,9",실시간온라인,NaN,0.0,"100%온라인:실시간온라인강의, 절대평가"